include ./makefile.posix

CFLAGS = -O2 -Wall -pipe -pthread
CXXFLAGS = ${CFLAGS}

progs = server_devpoll_nonblock

all: ${progs}

io_devpoll.o: io_devpoll.c io_devpoll.h

server_devpoll_nonblock: server_devpoll_nonblock.o io_devpoll.o io_server.o io_context.o io_common.o cmap.o
	${CC} ${CXXFLAGS} $^ ${LDFLAGS} -o $@.exe
