include ./makefile.unix

progs = server_epoll_nonblock

all: ${progs}

io_epoll.o: io_epoll.c io_epoll.h

server_epoll_nonblock: server_epoll_nonblock.o io_epoll.o io_server.o io_common.o
	${CC} ${CFLAGS} server_epoll_nonblock.o io_epoll.o io_server.o io_common.o ${LDFLAGS} -o $@.exe
