include ./Makefile.common

progs = server_kqueue_nonblock

all: ${progs}

kqueue_impl.o: kqueue_impl.c kqueue_impl.h

server_kqueue_nonblock: server_kqueue_nonblock.o io_common.o kqueue_impl.o
	${CC} ${CFLAGS} server_kqueue_nonblock.o io_common.o kqueue_impl.o ${LDFLAGS} -o $@
