include ./makefile.posix

CC = cc

progs = server_kqueue_nonblock$(EXT)

all: ${progs}

io_kqueue.o: io_kqueue.c io_kqueue.h

server_kqueue_nonblock$(EXT): server_kqueue_nonblock.o io_kqueue.o io_server.o io_context.o io_common.o cmap.o
	${CC} ${CFLAGS} $^ ${LDFLAGS} -o $@
