include ./makefile.common

TARGET = i586-legacy-linux-gnulibc1
CC = ${TARGET}-gcc
CXX = ${TARGET}-g++

progs = server_poll_nonblock

all: ${progs}

io_poll.o: io_poll.c io_poll.h

server_poll_nonblock: server_poll_nonblock.o io_poll.o io_server.o io_context.o io_common.o
	${CXX} ${CXXFLAGS} server_poll_nonblock.o io_poll.o io_server.o io_context.o io_common.o ${LDFLAGS} -o $@.exe
