CFLAGS ?= -O2 -Wall -pipe -D_XOPEN_SOURCE -pthread
CXXFLAGS ?= ${CFLAGS}
include ./makefile.common

progs = server_select_nonblock server_poll_nonblock

all: ${progs}

io_poll.o: io_poll.c io_poll.h

server_poll_nonblock: server_poll_nonblock.o io_poll.o io_server.o io_context.o io_common.o
	${CXX} ${CXXFLAGS} server_poll_nonblock.o io_poll.o io_server.o io_context.o io_common.o ${LDFLAGS} -o $@.exe
