include ./makefile.common

TARGET = i486-legacy-linuxaout
CC = ${TARGET}-gcc
CXX = ${TARGET}-g++
LDFLAGS = -lm

progs = server_poll_nonblock

all: ${progs}

io_poll.o: io_poll.c io_poll.h

server_poll_nonblock: server_poll_nonblock.o io_poll.o io_server.o io_context.o io_common.o cmap.o
	${CC} ${CXXFLAGS} $^ -lpoll ${LDFLAGS} -o $@.exe
