include ./makefile.posix

CC = cc
CXX = c++

progs = server_kqueue_nonblock

all: ${progs}

io_kqueue.o: io_kqueue.c io_kqueue.h

server_kqueue_nonblock: server_kqueue_nonblock.o io_kqueue.o io_server.o io_context.o io_common.o
	${CXX} ${CXXFLAGS} $^ ${LDFLAGS} -o $@.exe
